voyage_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Voyage:index" }
    methods:  GET

voyage_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Voyage:show" }
    methods:  GET

voyage_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Voyage:new" }
    methods:  [GET, POST]

voyage_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Voyage:edit" }
    methods:  [GET, POST]

voyage_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Voyage:delete" }
    methods:  DELETE

voyage_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Voyage:modifier" } 
    
voyage_recherche:
    path:     /recherchevoyage
    defaults: { _controller: "GestionProjetBundle:Voyage:recherche" }        