<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * bateauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bateauxRepository extends \Doctrine\ORM\EntityRepository
{
}
