<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * CiviliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiviliteRepository extends \Doctrine\ORM\EntityRepository
{
}
