<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    
         public function findHotelsBytitre($titre){
     // query builder routing: recherche1
           
    $query = $this->createQueryBuilder('a')
    ->where('a.titre like :titre')
    ->setParameter('titre', $titre.'%')
    ->orderBy('a.titre', 'ASC')
    ->getQuery();

     return  $query->getResult();
          
          
          
          
}   
}
