<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends \Doctrine\ORM\EntityRepository
{
    
 public function findVoyagesBytitre($titre){
     // query builder routing: recherche1
           
    $query = $this->createQueryBuilder('b')
    ->where('b.titre like :titre')
    ->setParameter('titre', $titre.'%')
    ->orderBy('b.titre', 'ASC')
    ->getQuery();

     return  $query->getResult();
          
          
          
          
}   
    
}
